name: Run Go Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: bdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Wait for DB
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "Postgres is up" && break
            echo "Waiting for DB..."
            sleep 3
          done

      - name: Run tests
        # env:
        #   BANK_POSTGRES_HOST: localhost:5432
        #   BANK_POSTGRES_USER: test
        #   BANK_POSTGRES_PASSWORD: test
        #   BANK_POSTGRES_DB: bank
        run: go test -v -cover ./...
